travis:
  secure:
    BINSTAR_TOKEN: PNRmspvZiKguKZnLPD7Rd0G5PHRyYe1y8MNxD7AwZz5y6N7xLUK1tb+iUwRaffigpKEQkACmD6MD3WMYwivxRrJ07qpMw5CSIxNserbI4rIyeUXuWoPzlPyuGUg0OB2LLDxEoMc2gggoG6Ij99N59eUatGoa8CKAhNu99H2peEGtv+SJqra8hog84sW3+pdovtxS7tJjZx+iREbEIsxYF6Kz8blUmjPSohn9cKy8WsdaPzboDu0m06n0uzXOsQf927yx7YrhYBrYmn3h57hFXw9sNi/Dg55kGY/UBpHkcFA0y3Kze8g5bDdePkkwGIFEYsJCBwa/rGe6OFSgmCVCX5wfqAH4ylwBaKY/5BV7Q4xf5PlJ8p8ka/rK/Wc63lcXLcJj84BjAfqs7eG6p8/mxST1q4zUdrBW/cPkOmV1bY/Bp4MpsDGPomAKEWiNlJkpJLVZQuIoP8y0d7tkxuSKykm6Zz0ZIAQ5FNDGp3eammeu1Tvg4OVwKBC3lfe3mzWeGq2U9nE+uC6s2mPXWERWAqi0PjPnJI98OV5IbWuSF2t6EFpGk5Y7iaRm6chyd9L9SH9GXX2c7/WYHWWnnbK6DVCJLcaSy1Oa4oPDEzNEMkIrsJmhfMgr+Ir9n0PHt6kiaUml8qr5VQiKTp7mx14QlGR+/B3bGIquCTZmV6M+0Ug=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
